import { spawn } from 'node:child_process';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { writeFileSync } from 'node:fs';
const CHROME = 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';
const PORT = 9254;
const SITE = 'https://wasi-shah-portfolio.vercel.app';
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const chrome = spawn(CHROME, ['--headless=new','--disable-gpu','--enable-unsafe-swiftshader','--hide-scrollbars',`--remote-debugging-port=${PORT}`,'--user-data-dir='+join(tmpdir(),'chrome-lb2-'+Date.now()),'--no-first-run','--window-size=1440,900','about:blank']);
async function ws(){for(let i=0;i<60;i++){try{const l=await(await fetch(`http://127.0.0.1:${PORT}/json/list`)).json();const p=l.find(x=>x.type==='page');if(p)return p.webSocketDebuggerUrl;}catch{}await sleep(200);}throw new Error('nd');}
const sock=new WebSocket(await ws());let id=0;const pend=new Map();
sock.onmessage=(e)=>{const m=JSON.parse(e.data);if(m.id&&pend.has(m.id)){pend.get(m.id)(m.result);pend.delete(m.id);}};
await new Promise(r=>(sock.onopen=r));
const send=(m,p)=>new Promise(res=>{const i=++id;pend.set(i,res);sock.send(JSON.stringify({id:i,method:m,params:p}));});
const ev=(expression)=>send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});
await send('Page.enable',{});await send('Runtime.enable',{});
await send('Emulation.setDeviceMetricsOverride',{width:1440,height:900,deviceScaleFactor:2,mobile:false});
await send('Page.navigate',{url:SITE+'/'});await sleep(4000);
await ev(`localStorage.setItem('ws-onboarded','1');localStorage.setItem('ws-cookie-consent','accepted');'ok'`);
await send('Page.reload',{});await sleep(12000);
await ev(`window.scrollTo(0,(2/4)*(document.documentElement.scrollHeight-window.innerHeight));'ok'`);await sleep(8000);
const c1=await ev(`(()=>{const c=[...document.querySelectorAll('article')].find(el=>el.textContent.includes('Portfolio World'));if(c){c.click();return 'clicked';}return 'no-card';})()`);console.log('card:',c1.result?.value);
await sleep(5000);
const c2=await ev(`(()=>{const b=[...document.querySelectorAll('.modal-enter button')].find(x=>(x.className||'').includes('cursor-zoom-in'));if(b){b.click();return 'clicked';}return 'no-img-btn:'+document.querySelectorAll('.modal-enter button').length;})()`);console.log('imgbtn:',c2.result?.value);
await sleep(5000);
const hasLb=await ev(`(() => document.body.innerHTML.includes('1 / 4') || !!document.querySelector('.z-\\[120\\]'))()`);console.log('lightbox present:',hasLb.result?.value);
const s=await send('Page.captureScreenshot',{format:'png'});
writeFileSync('<home>\\Downloads\\lb-bg.png',Buffer.from(s.data,'base64'));
console.log('shot lb-bg.png');
sock.close();chrome.kill();process.exit(0);
