-- Add local projects (not on GitHub)
insert into public.projects
  (id, exp_number, title, category, category_badge, tag, extra_badge, image, images, image_ratios, image_positions, col_span, description, tech, github_url, website_url, published, sort_order)
values
  ('obsidian-tasks', '06', 'Obsidian Tasks', 'code', 'Automation', 'Always-on-top task widget for Obsidian', 'PowerShell', '/images/obsidian-tasks.svg', array['/images/obsidian-tasks.svg'], array['auto'], array['center'], '4', 'A Windows PowerShell 5.1 + WPF always-on-top task widget that scans Obsidian markdown notes (frontmatter + checkboxes) and groups tasks by area with priorities, due dates, and company pills. Includes filters, sorting, tray minimize, a startup installer, and a watchdog.', array['PowerShell','WPF','Obsidian'], null, null, true, 4),

  ('expense-tracker', '07', 'Expense Tracker', 'code', 'Finance', 'Markdown-based expense logger', 'PowerShell', '/images/expense-tracker.svg', array['/images/expense-tracker.svg'], array['auto'], array['center'], '4', 'A Windows PowerShell 5.1 + WPF personal expense logger (GUI + CLI) that writes to a plain markdown file and computes monthly summaries with an auto-spend model. No database - the markdown file is the single source of truth.', array['PowerShell','WPF','Markdown'], null, null, true, 5),

  ('cash-app', '08', 'Cash', 'code', 'Fintech', 'Personal finance app + admin console', 'React', '/images/cash.svg', array['/images/cash.svg'], array['auto'], array['center'], '4', 'A personal finance system with a user app and a separate admin console, sharing one Supabase backend (6 tables, 2 edge functions, RLS). Includes onboarding with MPF calculation, expense categorization with auto-deduction, bills and debts, notices, session tracking, and a bilingual UI (Traditional Chinese / English).', array['React','TypeScript','Supabase','Tailwind'], null, null, true, 6),

  ('card-master', '09', 'Card-Master', 'code', 'Extension', 'Firefox card-game browser extension', 'Firefox', 'https://opengraph.githubassets.com/1/LYiHub/Card-master-browser-extension-public', array['https://opengraph.githubassets.com/1/LYiHub/Card-master-browser-extension-public'], array['auto'], array['center'], '4', 'A Firefox browser extension (card game). Forked from the original open-source repository by LYiHub.', array['JavaScript','Firefox Extension'], 'https://github.com/LYiHub/Card-master-browser-extension-public', null, true, 7),

  ('codex', '10', 'Codex', 'code', 'Security', 'Pentesting demos and reports', 'Security', '/images/codex.svg', array['/images/codex.svg'], array['auto'], array['center'], '4', 'Security demos and pentesting reports - clickjacking demonstrations, a return-map data-leak report, and other vulnerability demonstrations.', array['Pentesting','Security','HTML'], null, null, true, 8);
