-- Portfolio World: add a drawn-out architecture diagram + cleaner structure.
update public.projects set detailed_description = E'HOW IT IS BUILT\n- Frontend: React + Vite SPA; five rooms swap as the scrollbar drives a virtual camera.\n- 3D world: raw Three.js / WebGL - a raymarched black hole, planets, nebula sky, ripples, bloom.\n- Data: Supabase Postgres; Row-Level Security makes writes admin-only and reads public.\n- CMS (/admin): a tab per collection - create / edit / delete, upload, drag-to-crop, ratio + focus.\n- Media: uploads pass a Vercel function that checks the admin session, then land in ImageKit CDN.\n- Ops: CSP + HSTS, weekly Postgres backups, and a built-in client error log.\n\nARCHITECTURE\n┌──────────────┐          ┌──────────────┐\n│   Browser    │  content │   Supabase   │\n│ React+Three  │◀────────▶│ Postgres·RLS │\n└──────┬───────┘          └──────┬───────┘\n       │ media                   ▲ admin writes\n       ▼                         │\n┌──────────────┐  /api/upload  ┌─┴────────────┐\n│   ImageKit   │◀──────────────│    Vercel    │\n│     CDN      │               │  SPA + API   │\n└──────────────┘               └──────────────┘'
where id = 'portfolio-world';

-- Cash: add a flow diagram.
update public.projects set detailed_description = E'HOW IT IS BUILT\n- React 19 + TypeScript + Vite + Tailwind; two apps (user + admin) on one Supabase backend.\n- Postgres with Row-Level Security; two Edge Functions (admin via secret key, delete-account via JWT).\n- Onboarding computes Hong Kong MPF; expense categorisation auto-deducts the daily allowance.\n- Bilingual (Traditional Chinese / English) with avatar upload and cropping.\n\nARCHITECTURE\n┌────────────┐   anon key   ┌──────────────┐\n│  Cash App  │─────────────▶│   Supabase   │\n│  (user)    │              │  Postgres    │\n└────────────┘              │  + Auth      │\n┌────────────┐  x-admin-secret  └──────┬───┘\n│ Cash Admin │─────────────▶  admin Edge Function\n│ (developer)│                (service_role)\n└────────────┘'
where id = 'cash-app';

-- Face Overlay: add a signal-flow diagram.
update public.projects set detailed_description = E'HOW IT IS BUILT\n- Electron desktop app (Vite + JavaScript) with a floating, always-on-top window.\n- MediaPipe Face Landmarker runs in the renderer for real-time landmark tracking.\n- A canvas overlay maps expressions onto an avatar; the window is captured in OBS.\n\nPIPELINE\nWebcam ──▶ MediaPipe Face Landmarker ──▶ landmarks\n                                             │\n                                             ▼\n                    Avatar / overlay (canvas) ──▶ OBS capture'
where id = 'face-overlay';
